export const SF_SYMBOL_NAMES = [
  "camera",
  "photo.stack",
  "gearshape",
  "hand.raised",
  "checkmark.shield",
  "exclamationmark.shield",
  "gauge.with.needle",
  "bolt",
  "arrow.counterclockwise",
  "apple.terminal",
  "arrow.down.right.and.arrow.up.left",
  "arrow.right",
  "arrow.up",
  "arrow.turn.down.right",
  "arrow.triangle.2.circlepath",
  "arrow.triangle.branch",
  "arrow.up.left.and.arrow.down.right",
  "arrow.up.right.square",
  "arrow.up.to.line",
  "bubble.left",
  "checkmark",
  "checkmark.circle",
  "checkmark.circle.fill",
  "checkmark.seal",
  "chevron.left",
  "chevron.down",
  "chevron.right",
  "circle",
  "circle.dotted",
  "circle.lefthalf.filled",
  "clock",
  "doc.text",
  "ellipsis",
  "eye",
  "exclamationmark.octagon.fill",
  "exclamationmark.triangle",
  "folder",
  "line.3.horizontal",
  "line.3.horizontal.decrease",
  "lightbulb",
  "link",
  "list.bullet.indent",
  "magnifyingglass",
  "paperclip",
  "pencil",
  "person.crop.circle",
  "photo",
  "play.fill",
  "plus",
  "sidebar.right",
  "smallcircle.filled.circle",
  "square.3.layers.3d",
  "square.and.arrow.up",
  "stop.fill",
  "tag",
  "trash",
  "text.append",
  "tray.and.arrow.down",
  "wifi",
  "wifi.slash",
  "xmark",
  "xmark.circle.fill",
] as const;

export const SF_SYMBOL_SIZES = [12, 14, 16, 18, 20] as const;

export type SfSymbolName = (typeof SF_SYMBOL_NAMES)[number];
export type SfSymbolSize = (typeof SF_SYMBOL_SIZES)[number];
